version: '3'
services:
    game:
        build: ./Game
        ports:
            - "3000:3000"
        restart: on-failure 
        depends_on:
            - socket
    socket: 
        build: ./Sockets
        ports:
            - "6969:6969"
        restart: on-failure 


